export type DemoLocale = 'en' | 'zh'

export const DEMO_COPY = {
  en: {
    eyebrow: 'OPEN SOURCE / BROWSER EDITOR',
    title: 'Visible Surface Mockup',
    lede: 'Put artwork on the surface you can see. Depth and mask stay fixed while the print remains editable.',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    github: 'GitHub repository',
    chooseInputs: 'Choose inputs',
    localServiceSub: 'Local Depth Anything + SAM service.',
    fixtureSub: 'Bundled local model output.',
    sourcePhoto: 'Source photograph',
    designArtwork: 'Design artwork',
    sentLocal: 'The image is sent only to localhost:8080.',
    fixtureData: 'Bundled sample uses checked-in depth and mask data.',
    transparentHint: 'Transparent PNG/SVG works best. You can also drag the current artwork onto the preview.',
    dragArtwork: 'Drag artwork',
    dragPreview: 'Preview while moving · commit on release',
    useFixture: 'Use bundled fixture',
    useLocal: 'Use local models',
    wholeSurface: 'Use the whole image surface',
    wholeSurfaceDesc: 'The depth field is analyzed once for the full image. Every position remains draggable; Depth Anything V2 Small + SAM ViT-B are fixed locally.',
    localService: 'Local model service',
    bundledFixture: 'Bundled model fixture',
    export: 'Export',
    exportDesc: 'Preview and PNG export share the same Three.js scene.',
    exportPng: 'Export PNG',
    reset: 'Reset',
    showBefore: 'Show before',
    showMockup: 'Show mockup',
    localPreview: 'Local model preview',
    fixturePreview: 'Model fixture preview',
    releaseCommit: 'Release to commit',
    dragResizeRotate: 'Drag artwork · resize · rotate',
    surface: 'Surface',
    model: 'Model',
    state: 'State',
    before: 'before',
    ready: 'ready',
    loading: 'loading',
    oneDepthField: 'One fixed depth field',
    oneDepthDesc: 'The full image is analyzed once. Moving the design updates the UV field and its depth-connected region, so a drag never restarts model analysis.',
    depthMapping: 'Depth-aware mapping',
    depthDesc: 'A normalized depth map becomes a displaced grid. Arc-length coordinates give the print visible wrap and foreshortening.',
    twoModels: 'Two model roles',
    twoModelsDesc: 'Depth Anything V2 Small describes how the surface bends; SAM ViT-B provides optional semantic candidates.',
    docsIncluded: 'README + architecture docs included',
    placementCommitted: 'Placement committed',
    designCommitted: 'Design committed to the visible surface',
    exported: (width: number, height: number) => `Exported ${width} × ${height} PNG`,
    placementReset: 'Placement reset',
    sourceLoaded: 'Source loaded locally',
    designLoaded: 'Design loaded locally',
    bundledLoaded: 'Bundled sample loaded',
    localEnabled: 'Local Depth Anything + SAM service enabled',
  },
  zh: {
    eyebrow: '开源项目 / 浏览器编辑器',
    title: '可见曲面 Mockup',
    lede: '把设计放到照片里看得见的表面上，固定深度场，让贴图保持可编辑。',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    github: 'GitHub 仓库',
    chooseInputs: '选择输入',
    localServiceSub: '本地 Depth Anything + SAM 服务。',
    fixtureSub: '仓库内置的本地模型结果。',
    sourcePhoto: '源图片',
    designArtwork: '设计稿',
    sentLocal: '图片只会发送到 localhost:8080。',
    fixtureData: '内置样例使用仓库中的深度和 mask 数据。',
    transparentHint: '透明 PNG/SVG 效果最好，也可以把当前设计直接拖到预览区。',
    dragArtwork: '拖动设计稿',
    dragPreview: '移动中预览 · 松开后提交',
    useFixture: '使用内置样例',
    useLocal: '使用本地模型',
    wholeSurface: '使用整张图片表面',
    wholeSurfaceDesc: '整张图片只分析一次深度场，所有位置都可以拖动；Depth Anything V2 Small + SAM ViT-B 固定在本地运行。',
    localService: '本地模型服务',
    bundledFixture: '内置模型样例',
    export: '导出',
    exportDesc: '预览和 PNG 导出复用同一个 Three.js 场景。',
    exportPng: '导出 PNG',
    reset: '重置',
    showBefore: '查看原图',
    showMockup: '查看 Mockup',
    localPreview: '本地模型预览',
    fixturePreview: '模型样例预览',
    releaseCommit: '松开后提交',
    dragResizeRotate: '拖动设计稿 · 缩放 · 旋转',
    surface: '表面',
    model: '模型',
    state: '状态',
    before: '原图',
    ready: '就绪',
    loading: '加载中',
    oneDepthField: '固定深度场',
    oneDepthDesc: '整张图片只分析一次。移动设计稿只更新 UV 和当前深度连通区域，不会重新调用模型。',
    depthMapping: '深度映射',
    depthDesc: '归一化深度图会转换成位移网格，弧长坐标让贴图呈现曲面包裹和透视变化。',
    twoModels: '两个模型的作用',
    twoModelsDesc: 'Depth Anything V2 Small 描述表面如何弯曲；SAM ViT-B 提供可选的语义候选区域。',
    docsIncluded: '包含 README 和架构文档',
    placementCommitted: '位置已提交',
    designCommitted: '设计稿已提交到可见表面',
    exported: (width: number, height: number) => `已导出 ${width} × ${height} PNG`,
    placementReset: '位置已重置',
    sourceLoaded: '源图片已加载到本地',
    designLoaded: '设计稿已加载到本地',
    bundledLoaded: '已加载内置样例',
    localEnabled: '已启用本地 Depth Anything + SAM 服务',
  },
} as const
